#!/bin/sh

for i in 100 111 112 113; do
    ip="192.168.122.$i"
    port="$((4000+$i))"

    shellinaboxd \
	--background="`dirname $0`/shellinaboxd.$i.pid" \
	--localhost-only \
	--no-beep \
	--disable-ssl \
	--port=$port \
	--css=shellinabox.css \
	--service /:florian:florian:HOME:"env SSH_AUTH_SOCK=$SSH_AUTH_SOCK ssh root@${ip}"
done
